services:
  backend-config:
    build: ./backend
    volumes:
      - ./backend:/rails
    depends_on:
      - db
    env_file:
      ".env"
    environment:
      RAILS_ENV: development
  backend-server:
    extends: backend-config
    command: >
      ./bin/rails server -b 0.0.0.0
    restart: always
