services:
  db:
    image: postgres
    volumes:
      - posterr-psql-data:/var/lib/postgresql/data
    env_file:
      ".env"
    restart: always
  backend:
    extends:
      file: backend.yml
      service: backend-server
    ports:
      - 5000:3000
    environment:
      RAILS_ENV: test
  frontend:
    extends:
      file: frontend.yml
      service: frontend-config
    ports:
      - 3000:3000
    restart: always
  cypress:
    build: ./end-to-end
    depends_on:
      - backend
      - frontend
    entrypoint: npx cypress
    profiles:
      - end-to-end

volumes:
  posterr-psql-data:
