services:
  db:
    image: postgres
    volumes:
      - posterr-psql-data:/var/lib/postgresql/data
    env_file:
      ".env"
    restart: always
  backend:
    extends:
      file: backend.yml
      service: backend-server
    ports:
      - 5000:3000
    restart: always
  rake:
    extends:
      file: backend.yml
      service: backend-config
    entrypoint: ./bin/rake
    profiles:
      - rake
  rails:
    extends:
      file: backend.yml
      service: backend-config
    entrypoint: ./bin/rails
    profiles:
      - rails
  frontend:
    extends:
      file: frontend.yml
      service: frontend-config
    ports:
      - 3000:3000
    restart: always
  npm:
    extends:
      file: frontend.yml
      service: frontend-config
    entrypoint: npm
    profiles:
      - npm

volumes:
  posterr-psql-data:
