services:
  db:
    image: postgres
    volumes:
      - posterr-psql-data:/var/lib/postgresql/data
    env_file:
      ".env"
    restart: always
  backend-test:
    extends:
      file: backend.yml
      service: backend-server
    ports:
      - 5000:3000
    environment:
      RAILS_ENV: test
    profiles:
      - end-to-end
  backend:
    extends:
      file: backend.yml
      service: backend-server
    ports:
      - 5000:3000
  rake:
    extends:
      file: backend.yml
      service: backend-config
    entrypoint: ./bin/rake
    profiles:
      - rake
  rails:
    extends:
      file: backend.yml
      service: backend-config
    entrypoint: ./bin/rails
    profiles:
      - rails
  frontend:
    extends:
      file: frontend.yml
      service: frontend-config
    ports:
      - 3000:3000
    restart: always
  npm:
    extends:
      file: frontend.yml
      service: frontend-config
    entrypoint: npm
    profiles:
      - npm
  cypress:
    build: ./end-to-end
    depends_on:
      - backend-test
      - frontend
    # entrypoint: npx cypress open
    profiles:
      - end-to-end

volumes:
  posterr-psql-data:
