services:
  db:
    image: postgres
    volumes:
      - posterr-psql-data:/var/lib/postgresql/data
    env_file:
      ".env"
    restart: always
  backend-config:
    build: ./backend
    volumes:
      - ./backend:/rails
    depends_on:
      - db
    env_file:
      ".env"
    profiles:
      - none
  backend-server:
    extends: backend-config
    command: >
      ./bin/rails server -b 0.0.0.0
    restart: always
    profiles:
      - none
  backend:
    extends: backend-server
    ports:
      - 3000:3000
    profiles:
      - prod
  backend-dev:
    extends: backend-server
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000
    profiles:
      - dev
  backend-test:
    extends: backend-config
    command: ./bin/bundle exec rspec spec
    environment:
      RAILS_ENV: test
    profiles:
      - backend-test
  db-migrate-dev:
    extends: backend-config
    command: ./bin/rake db:migrate
    environment:
      RAILS_ENV: development
    profiles:
      - migrate-dev
  db-rollback-dev:
    extends: backend-config
    command: ./bin/rake db:rollback
    environment:
      RAILS_ENV: development
    profiles:
      - rollback-dev

volumes:
  posterr-psql-data:
